on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:1.2.4
    steps:
    - uses: actions/checkout@v4
    - name: Package
      run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project ggj2025.wlp --output deploy/ --credentials "$WLE_CREDENTIALS"
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-deploy
        path: deploy/
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download package artifact
      uses: actions/download-artifact@v4
      with:
        name: game-deploy
        path: deploy
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: deploy